name: Trigger auto deployment for digigrow-api-public-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/digigrow-api-public-prod-AutoDeployTrigger-23a0e9e6-91d7-4513-a565-4854c5cece6c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DIGIGROWAPIPUBLICPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DIGIGROWAPIPUBLICPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DIGIGROWAPIPUBLICPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 2309180040009788.azurecr.io
          registryUsername: ${{ secrets.DIGIGROWAPIPUBLICPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DIGIGROWAPIPUBLICPROD_REGISTRY_PASSWORD }}
          containerAppName: digigrow-api-public-prod
          resourceGroup: rg-config-test
          imageToBuild: 2309180040009788.azurecr.io/digigrow-api-public-prod:${{ github.sha }}
          dockerfilePath: Dockerfile


